### PR TITLE
Debug and improve MacOS sim-only development.

### PR DESCRIPTION
**Pull request by jpreiss**
- Don't try to import the Linux-only joystick module.
- Anaconda environment definition file to avoid version issues. Also works on Linux.
- Use setup.py instead of manual compiler invocation for `_cffirmware.so`. (Plays nicer with Anaconda's include and lib dirs for C extensions.)
- Update installation docs.

### CODE REVIEW

**Comment by jpreiss** [comment]
Good idea, I'll look into it. I never used Travis but if it's easy enough to set up another config, I'll just add it to this pull request.

**Comment by jpreiss** [comment]
hmm, it would be much cleaner if we could create a separate `.travis.yml` file without all the ROS stuff but github only allows one per repo.

**Comment by whoenig** [comment]
True, but I think you can use conditional statements per target platform - a bit ugly but better than nothing for now.

**Comment by jpreiss** [comment]
Weird, the git recursive submodule update is failing on mac. [link](https://travis-ci.org/USC-ACTLab/crazyswarm/jobs/617934690?utm_medium=notification&utm_source=github_status)

**Comment by jpreiss** [comment]
it seems that Travis itself does a recursive git submodule update. I think we did it non-recursively in `build.sh` because the recursive one created some problem in the past. But then how was Travis working OK before?

**Comment by jpreiss** [comment]
Fixed that by configuring Travis not to do a recursive clone, but now something is wrong with the libmotioncapture build on Linux/ROS. @whoenig can you take a look? I'm not familiar with how the different motion capture SDK builds are configured.

**Comment by whoenig** [comment]
This is very strange. It seems to be related to PCL, see https://stackoverflow.com/questions/37369369/compiling-pcl-1-7-on-ubuntu-16-04-errors-in-cmake-generated-makefile. You could try installing `libproj-dev` as part of the travis script. I have no idea why that would suddenly be a problem. It seems to be unrelated to any of the changes you have been making.

**Comment by jpreiss** [comment]
Added `libproj-dev`, but now we fail on `-lvtkproj4`.

I think the problem is probably related to the fact that I now install the non-ROS dependencies before the ROS ones, instead of after. I guess we were pulling those dependencies transitively via some ROS package.

**Comment by whoenig** [comment]
We could add the second hack to libmotioncapture/CMakeLists.txt from the stackoverflow post (add `list(REMOVE_ITEM PCL_LIBRARIES "vtkproj4")`). Not sure if that will have any negative effect on 18.04.

**Comment by jpreiss** [comment]
We could also just flip the order back to how it was before. I moved the `libpcl-dev` installation before the ROS installation because it was in the same line as `swig`, etc., needed for the sim-only build, but we could separate them.

There is no current use case where someone would need `libobjecttracker` and `libmotioncapture` but not ROS, right?

**Comment by whoenig** [comment]
Yeah, that would also be a solution for CI. I also want to drop support for 16.04 at some point and I have not seen any issues on 18.04 so far with the build (however, Travis did not support 18.04 last time I checked...).

Yes, to my knowledge there is no use case to use those two libraries without ROS.

**Pull request merged**
