### PR TITLE
remove symlinked/autogenerated CMakeLists

### LINKED ISSUE #267: CMakeList.txt tracked in Git
Hi

I noticed that the autogenerated `CMakeList.txt` in `ros_ws/src` is included in the `crazyswarm` repo. This creates an issue when using a ROS version other than Kinetic and working on different branches, since the changed symbolic link results in a dirty working tree. I am not sure about best practices for ROS, but to me it seems like this file should not be tracked in Git.

Thanks for the support!

### PR DESCRIPTION
**Pull request by acxz**
closes #267

### CODE REVIEW

**Comment by acxz** [comment]
closing/reopening to refresh ci build

**Comment by jpreiss** [comment]
Thanks! Can you also add a line in the root `.gitignore` to ensure this doesn't get added again by a careless `git add .`?

**Comment by acxz** [comment]
Sure

**Comment by acxz** [comment]
@jpreiss added

**Pull request merged**
