### PR TITLE
Remove dependency to crazyflie_ros by adding msg/srv directly here.

### PR DESCRIPTION
**Pull request by whoenig**
Crazyflie_ros will be deprecated in favor of the Crazyswarm. In order
to avoid unnecessary deep dependencies, we move all the custom messages
and services directly into the Crazyswarm project.

This change also avoids to have crazyflie_cpp twice. Now, only the one
that comes with crazyflie_tools is used.

### CODE REVIEW

**Comment by whoenig** [comment]
Some more background: The goal is to eventually switch to crazyflie-link-cpp as backend, which will solve many longstanding communication issues. In particular, we should be able to upload a trajectory while flying, once the full system is working! It also resolves many other bugs that were caused by using a unreliable link. This is work in progress (see https://github.com/whoenig/crazyflie_tools/tree/dev-crazyflie-link-cpp). This PR is the first step to prepare the Crazyswarm to get a major backend switch later on.

**Comment by jpreiss** [comment]
The code changes look good to me. `crazyflie-link-cpp` will be a big step forward!

Looks like some of the CI timed out or failed unnaturally, re-running the jobs.

In the streaming setpoint tutorial, there are some other places that refer to `crazyflie_ros` that should probably be changed to "the ROS layer" or similar.

Might also be good to grep the whole directory for `crazyflie_ros` and double-check for other references in docs, comments, etc.

**Review by jpreiss — COMMENTED** [review]
The code changes look good to me. `crazyflie-link-cpp` will be a big step forward!

Looks like some of the CI timed out or failed unnaturally, re-running the jobs.

In the streaming setpoint tutorial, there are some other places that refer to `crazyflie_ros` that should probably be changed to "the ROS layer" or similar.

Might also be good to grep the whole directory for `crazyflie_ros` and double-check for other references in docs, comments, etc.

**Comment by whoenig** [comment]
Fixed - thanks!

**Pull request merged**
