### PR TITLE
notifySetpointsStop, cmdVelocityWorld, and example

### PR DESCRIPTION
**Pull request by jpreiss**
- `notifySetpointsStop` support for https://github.com/bitcraze/crazyflie-firmware/pull/560
- `cmdVelocityWorld` support (already in `pycrazyswarm` and `crazyflie_ros` but forgot we have a fork of `crazyflie_server.cpp` here that needs to track it)
- An example script using both

### CODE REVIEW

**Comment by jpreiss** [comment]
This will start building correctly after https://github.com/whoenig/crazyflie_cpp/pull/14 is accepted and we can update the submodule transitively via `crazyflie_ros`.

**Comment by MauroPfister** [comment]
Hi

Is there a reason that this PR has not been merged yet? It seems like https://github.com/whoenig/crazyflie_cpp/pull/14 has been accepted. Moreover, are there plans to update the `crazyflie-firmware` submodule to the newest version anytime soon so the new `notifySetpointStop` can be used?

Thanks for your work!

**Comment by jpreiss** [comment]
We did not get to complete testing due to covid-19. We plan to do both of these things after we can finish testing. I am hoping to get to it in the next few weeks, but no guarantees.

Have you tried running this branch yourself? If it worked, then I would be OK merging the PR based on outside testing.

**Comment by MauroPfister** [comment]
That sounds promising!

I will have some time this week to test the features of this branch. Is there a script you would like me to test? Otherwise I will try to take off, fly a circle (in low-level mode) and then land again. I am quite new to `crazyswarm` so maybe it would be good if you verified the branch yourself too.

**Comment by MauroPfister** [comment]
I started playing around with the`highlevel` branch but encountered some problems. Here is what I did so far:

- Building and flashing master branch of `crazyflie-firmware` and `crazyflie2-nrf-firmware`
- Updating `crazyflie_ros` to master
- Adding `notifySetpointsStop` related code from `crazyflie_ros/crazyflie_driver/src/crazyflie_server.cpp` in `crazyswarm/src/crazyswarm_server.cpp` because without that the service did not appear and  `rospy.wait_for_service(prefix + "/notify_setpoints_stop")` in `crazyflie.py` blocked. I'm not sure if this is correct but it build successfully. 
- Change `StartTrajectory` to `NotifySetpoinsStop` when creating proyyservice in `crazyflie.py`

However, there is still a problem I could not fix yet: When calling `cf.notifySetpointsStop()` the Python script crashes because of a missmatch of arguments (missing `groupMask`). As soon as I am back at my computer I will upload the stack trace.

**Comment by jpreiss** [comment]
Thanks for the testing.

You are correct in porting the code from `crazyflie_ros/.../crazyflie_server.cpp` to `crazyswarm/.../crazyswarm_server.cpp`.

The `groupMask` argument should not be required because `notifySetpointsStop` is not a broadcast-mode command. The script crash sounds like a bug. Once you upload your stack trace I can track it down.

**Comment by MauroPfister** [comment]
Sorry for the delay. Below the python script I execute and its stack trace. Right now the drone just drops to the floor when the error occurs. Let me know if you need more information, I am happy to help.

```python
#!/usr/bin/env python

import numpy as np
from pycrazyswarm import *

Z = 1.0

if __name__ == "__main__":
    swarm = Crazyswarm()
    timeHelper = swarm.timeHelper
    allcfs = swarm.allcfs

    allcfs.takeoff(targetHeight=Z, duration=1.0+Z)
    timeHelper.sleep(1.5+Z)
    for cf in allcfs.crazyflies:
        x = 0
        while x < 0.5:
            pos = np.array([x, 0, Z])
            cf.cmdPosition(pos)
            x += 0.05
            timeHelper.sleep(0.05)

        cf.notifySetpointsStop(remainValidMillisecs=100)

    print("press button to continue...")
    swarm.input.waitUntilButtonPressed()

    allcfs.land(targetHeight=0.02, duration=1.0+Z)
    timeHelper.sleep(1.0+Z)
```

```
Warning: No joystick found!
Traceback (most recent call last):
  File "high_low_level_switch.py", line 34, in <module>
    cf.notifySetpointsStop(remainValidMillisecs=100)
  File "/home/lis/Develop/crazyswarm_USC/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflie.py", line 286, in notifySetpointsStop
    self.notifySetpointsStopService(remainValidMillisecs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 498, in call
    request = rospy.msg.args_kwds_to_message(self.request_class, args, kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msg.py", line 122, in args_kwds_to_message
    return data_class(*args)
  File "/home/lis/Develop/crazyswarm_USC/ros_ws/devel/lib/python2.7/dist-packages/crazyflie_driver/srv/_NotifySetpointsStop.py", line 35, in __init__
    super(NotifySetpointsStopRequest, self).__init__(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genpy/message.py", line 344, in __init__
    raise TypeError('Invalid number of arguments, args should be %s' % str(self.__slots__) + ' args a
re' + str(args))
TypeError: Invalid number of arguments, args should be ['groupMask', 'remainValidMillisecs'] args are
(100,)
```

**Comment by MauroPfister** [comment]
@jpreiss I have been using this branch (with the above modifications) successfully to control a "swarm" of six crazyflies. As far as I can tell, the switch from low level to high level works fine now. Would you like me to add my modifications to your PR (not sure if this is possible) or will you include them yourself?

**Comment by jpreiss** [comment]
Hi Mauro, thanks so much for your testing and bug fixes. This is a very helpful contribution. Please create a pull request of your own branch against jpreiss:highlevel. I will resolve the merge conflicts.

**Comment by jpreiss** [comment]
Hi Mauro, is there any public branch with your changes? I am in the lab, and can test on our hardware.

**Comment by MauroPfister** [comment]
Hi @jpreiss, sorry for not answering, I was a bit busy yesterday and did not have time to create a PR yet. Will hopefully get to it on Monday or Tuesday.

**Comment by MauroPfister** [comment]
@jpreiss Finally had the time to create a pull request (https://github.com/jpreiss/crazyswarm/pull/1). I hope everything is okay, it is the first time I am doing this.

**Pull request merged**
