### PR TITLE
fix a bug in led ring

### PR DESCRIPTION
**Pull request by zjh95817**
The setLEDColor function not work for the led ring, for a lack of "ring/effect"

### CODE REVIEW

**Comment by jpreiss** [comment]
This is by design, because if a client wants to change the LED colors in a fast loop it would waste bandwidth. But that's a rare case and the current behavior is confusing. We could add a kwarg `sendRingMode=True` to get the best of both worlds.

**Comment by zjh95817** [comment]
> This is by design, because if a client wants to change the LED colors in a fast loop it would waste bandwidth. But that's a rare case and the current behavior is confusing. We could add a kwarg `sendRingMode=True` to get the best of both worlds.

I got it. Then I think the code in the example led_colors.py should set the "ring/effect" first or it can't work.

**Comment by jpreiss** [comment]
That is probably a good idea. I normally set it in the launch file, but it's easy to forget to do that. If you would like to change this PR to implement that, I will merge it.

**Comment by zjh95817** [comment]
> That is probably a good idea. I normally set it in the launch file, but it's easy to forget to do that. If you would like to change this PR to implement that, I will merge it.

Fine. I'll make it.

**Comment by jpreiss** [comment]
example fixed in d5e19a3.

**Pull request closed without merging**
