### PR TITLE
update bitcraze python submodules

### PR DESCRIPTION
**Pull request by acxz**
Just a routine upgrade for the python libraries from bitcraze

Was having some issues with the submodules version of `crazyflie-clients-python`, specifically `PyQt5` was a pinned dependency.

In any case went ahead and updated our `crazyflie-clients-python` and `crazyflie-lib-python` submodules to the current latest release.

### CODE REVIEW

**Comment by jpreiss** [comment]
It looks like something related to [this problem](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) has broken both the ROS setup and Conda setup actions we use in our CI. We should fix the CI before accepting new pull requests.

**Comment by acxz** [comment]
@jpreiss yeah that prob appropriate to do, I submitted #275 to fix the CI. If you could take a look at it, that would be great.

**Comment by acxz** [comment]
closing/reopening to refresh ci build

**Comment by jpreiss** [comment]
Thank you for your contributions! Maintenance from the community really helps keep the project moving. We appreciate it.

**Pull request merged**
