### PR TITLE
Python3 Support

### PR DESCRIPTION
**Pull request by Zhenghao-Dai**

### CODE REVIEW

**Comment by Zhenghao-Dai** [comment]
@jpreiss It looks like the setup.py has also been changed during the development of bvca compare to master. What should we do?

**Comment by jpreiss** [comment]
For the conda builds, we need to replace the `matplotlib=2.1` requirement in `conda_env.yaml` with just `matplotlib`. Version 2.1 is older than the oldest version available for Python 3. It won't cause a problem - versions newer than 2.1 cause `vispy` to generate a warning, but not an error.

**Comment by jpreiss** [comment]
For the Python 2 ROS builds, it appears that the `CSW_PYTHON` environment variable ends up empty. Look at the logs:

    setup.py build_ext --inplace
    make: setup.py: Command not found

It fails because it tries to run `setup.py` as a command. I am not sure why this is happening, need to investigate more.

**Comment by jpreiss** [comment]
For the Python 3 ROS build, it fails because the ROS VRPN package is not available. We can fix this once Wolfgang accepts https://github.com/USC-ACTLab/libmotioncapture/pull/9.

**Comment by jpreiss** [comment]
I think the `setup.py` issue is caused by your changes to `build.sh` and `buildSimOnly.sh`. You are trying to pass `CSW_PYTHON` as an argument, but it is already set as an environment variable by the CI. Try reverting those changes.

**Comment by whoenig** [comment]
What is missing/failing here? Would be nice to get the Crazyswarm working with ROS Noetic.

**Comment by jpreiss** [comment]
It was already merged in #261. This PR is a first draft that we can close.

**Pull request closed without merging**
