### PR TITLE
Remove Crazyradio firmware upgrade from the docs

### PR DESCRIPTION
**Pull request by The-SS**

### CODE REVIEW

**Comment by The-SS** [comment]
Ok, so the docs should actually refer the users to [https://github.com/bitcraze/crazyradio-firmware](https://github.com/bitcraze/crazyradio-firmware) for flashing the Crazyradio (since crazyradio-firmware is not longer part of crazyswarm). 
Regarding the crazyflie firmware, it also seems that crazyswarm is many commits behind the current Bitcraze firmware. So, using the precompiled binaries is not recommended and instead users should use the more recent official firmware and flash the crazyflies with cfclient. 

To summarize, users should:
- get the crazyradio firmware from Bitcraze [https://github.com/bitcraze/crazyradio-firmware](https://github.com/bitcraze/crazyradio-firmware) and follow the instructions there
- get cfclient from Bitcraze [https://github.com/bitcraze/crazyflie-clients-python](https://github.com/bitcraze/crazyflie-clients-python) and install that.
- get the crazyflie firmware from Bitcraze [https://github.com/bitcraze/crazyflie-firmware](https://github.com/bitcraze/crazyflie-firmware) and flash with cfclient

Is that correct?

**Comment by jpreiss** [comment]
Crazyswarm always references a version of the firmware that has been flight-tested with Crazyswarm. Usually @whoenig or I do the testing, but users can report a successful test too. If you use a newer firmware version and find that it works, please create a PR that updates the submodule.

If the firmware update goes along with a new Crazyswarm feature, the test should make sure to cover that feature. Otherwise just make sure something simple like `figure8_csv.py` still works.

**Comment by The-SS** [comment]
Ok. Sounds good. I'll start with the current tested firmwares and possibly update them to see if things still work.

**Comment by whoenig** [comment]
I just think we can remove the remaining submodules (python client, python lib, crazyradio firmware), remove the prebuilt folder, and then document for new Bitcraze firmware releases that those have been flight tested. Note that Bitcraze is now also testing some Crazyswarm functionality (no real flights yet), see https://github.com/bitcraze/crazyflie-testing/pull/13.

**Comment by jpreiss** [comment]
but we need the firmware in a known location to compile the firmware modules used by `CrazyflieSim`. I agree the others could go.

**Comment by whoenig** [comment]
Good point - yes, the firmware itself needs to stay and should probably just point to a tagged release, rather than the master branch.

**Comment by whoenig** [comment]
Closing this, since we integrated all the discussed changes in https://github.com/USC-ACTLab/crazyswarm/pull/473.

**Pull request closed without merging**
