### PR TITLE
#232 visVispy video output via ffmpeg

### PR DESCRIPTION
**Pull request by jpreiss**
Enables video recording using the VisPy visualizer. Uses https://github.com/kkroening/ffmpeg-python, a thin wrapper for interacting with an `ffmpeg` process.

Much more control could be exposed in the future over resolution, encoding, etc.

Unit test disabled on Travis because the Travis machine can't create an X11 OpenGL context. Would need to get Mesa software OpenGL working, which seems annoying.

### CODE REVIEW

**Comment by jpreiss** [comment]
There is still a big quality advantage over screen capture, but I like your idea.

**Comment by jpreiss** [comment]
One possible issue with your design: in `finishVideoOutput` the current code sends `EOF` to the `ffmpeg` process's `stdin` and then waits for it to close. This will ensure that we don't leave the `ffmpeg` process running.

`pycrazyswarm` does not have any mechanism for the script to tell the system "I'm done", so it's not clear where this code would go in your design. We could create a `__del__` method on `TimeHelper`, but there is no guarantee that it will ever run.

Maybe we could make `CrazyflieServer` or `TimeHelper` a context manager object?

**Comment by whoenig** [comment]
We could use an atexit handler https://docs.python.org/3/library/atexit.html. I have not used that before, but rospy has a concept like that too (http://wiki.ros.org/rospy/Overview/Initialization%20and%20Shutdown). Of course if we are simulating, we don't want a dependency to ROS, but I assume internally they implemented it with the atexit concept.

**Comment by jpreiss** [comment]
I implemented the `atexit` handler. It needs a complicated unit test to run the video generation in a separate process that exits cleanly, but the user experience of adding a flag to get video output is really nice.

**Comment by whoenig** [comment]
Looks great!

**Comment by whoenig** [comment]
Any reason why we didn't end up merging this? If you want, I can try to resolve those conflicts @jpreiss ?

**Comment by jpreiss** [comment]
I am not sure why. Maybe it just became conflicted and I never got around to resolving the conflicts. I think we can go ahead and merge it.

The change in `installation.rst` should be reverted because the doc overhaul happened after this PR.

I expect the changes in `CrazyflieSim` will need a manual merge.

**Comment by jpreiss** [comment]
There are a lot of conflicts to resolve. I will do it.

**Pull request merged**
